[package]
name = "xmrigiso-server-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.0", features = ["derive"] }
curl = "0.4"
log = "0.4"
env_logger = "0.9"
openssl = "0.10"
tokio = { version = "1", features = ["full"] }
socks = "0.3"
